#!/bin/sh

GIT_REMOTE=origin

while getopts o: ch; do
	case $ch in
		(o) GIT_REMOTE=$OPTARG;;
	esac
done
shift $(( $OPTIND - 1 ))

if [ -z "$1" ]; then
	echo "USAGE: git-pr <pull-request id>" >&2
	exit 1
fi

git fetch $GIT_REMOTE pull/$1/head:pull/$1 &&
	git checkout pull/$1
